import { WorkflowContext, getAffectedDocTargets, generateDocBranchName } from './common';
import { AgentOrchestrator } from '../agent/orchestrator';
import { buildUpdatePromptWithTools } from '../agent/prompts';
import { logger } from '../util/logger';
import { SessionStore } from '../agent/session-store';
import { DocTarget } from '../util/config-loader';

/**
 * Full update workflow with file editing and PR creation
 * This handles both same-repo and cross-repo documentation updates
 */
export async function updateWorkflowFull(
  ctx: WorkflowContext,
  apiKey: string,
  sessionStore: SessionStore,
  userInstructions?: string
): Promise<void> {
  logger.info({ project: ctx.event.project, mrId: ctx.event.mrId }, 'Starting full update workflow');

  // Check if any doc targets are affected
  const affectedTargets = getAffectedDocTargets(ctx);

  if (affectedTargets.length === 0) {
    await ctx.platform.postComment(
      ctx.event.project,
      ctx.event.mrId,
      '## Doc-Bot\n\nNo documentation targets are affected by these changes.'
    );
    return;
  }

  // Separate same-repo and cross-repo targets
  const sameRepoTargets = affectedTargets.filter((t) => t.mode === 'same-repo');
  const crossRepoTargets = affectedTargets.filter((t) => t.mode === 'cross-repo');

  logger.info(
    { sameRepoCount: sameRepoTargets.length, crossRepoCount: crossRepoTargets.length },
    'Processing documentation targets'
  );

  // Process same-repo updates
  if (sameRepoTargets.length > 0) {
    await processSameRepoUpdates(ctx, apiKey, sessionStore, sameRepoTargets, userInstructions);
  }

  // Process cross-repo updates
  if (crossRepoTargets.length > 0) {
    await processCrossRepoUpdates(ctx, apiKey, sessionStore, crossRepoTargets, userInstructions);
  }

  logger.info('Full update workflow completed');
}

/**
 * Process same-repo documentation updates
 */
async function processSameRepoUpdates(
  ctx: WorkflowContext,
  apiKey: string,
  sessionStore: SessionStore,
  targets: DocTarget[],
  userInstructions?: string
): Promise<void> {
  logger.info({ targetCount: targets.length }, 'Processing same-repo updates');

  // Clone source repo
  const cloneUrl = await ctx.platform.getAuthenticatedCloneUrl(ctx.event.project);
  const branchName = generateDocBranchName(ctx.event);

  const { git, workDir } = await ctx.gitManager.clone({
    repoUrl: cloneUrl,
    branch: ctx.event.targetBranch, // Base from target branch
  });

  try {
    // Create new branch for doc updates
    await ctx.gitManager.createBranch(git, branchName);

    // Run agent with file operation tools enabled
    const agent = new AgentOrchestrator({
      apiKey,
      model: ctx.config.model,
      maxTurns: ctx.config.maxTurns,
      workDir,
      styleGuide: ctx.styleGuide,
    });

    const prompt = buildUpdatePromptWithTools(
      ctx.diff,
      targets,
      ctx.changedFiles,
      ctx.styleGuide,
      userInstructions,
      true // same-repo mode
    );

    const result = await agent.run(prompt, undefined, true); // Enable tools

    // Store session for potential revisions
    sessionStore.set(
      {
        platform: ctx.event.platform,
        project: ctx.event.project,
        mrId: ctx.event.mrId,
      },
      result.sessionId
    );

    // Check if any files were modified
    if (result.modifiedFiles.length === 0) {
      await ctx.platform.postComment(
        ctx.event.project,
        ctx.event.mrId,
        `## 📝 Doc-Bot Analysis\n\n${result.response}\n\n*No documentation changes were needed.*\n\n<sub>Cost: $${result.cost.toFixed(4)} | Turns: ${result.turns}</sub>`
      );
      return;
    }

    // Commit changes
    await ctx.gitManager.commit(git, {
      files: result.modifiedFiles,
      message: `docs: update documentation for ${ctx.event.project} MR !${ctx.event.mrId}\n\nAutomatic documentation updates based on code changes.\n\nSee: ${ctx.event.repoUrl}/merge_requests/${ctx.event.mrId}`,
      authorName: 'Doc-Bot',
      authorEmail: 'doc-bot@localhost',
    });

    // Push branch
    await ctx.gitManager.push(git, branchName);

    // Create MR/PR
    const mrResult = await ctx.platform.openMR(ctx.event.project, {
      sourceBranch: branchName,
      targetBranch: ctx.event.targetBranch,
      title: `docs: Update documentation for !${ctx.event.mrId}`,
      description: `## Automated Documentation Updates\n\nThis MR contains documentation updates based on code changes in !${ctx.event.mrId}.\n\n### Changes\n\n${result.modifiedFiles.map((f) => `- \`${f}\``).join('\n')}\n\n### Agent Summary\n\n${result.response}\n\n---\n\n<sub>Generated by Doc-Bot | Cost: $${result.cost.toFixed(4)} | Turns: ${result.turns}</sub>`,
    });

    const mrUrl = mrResult.webUrl;
    // Post comment with MR link
    await ctx.platform.postComment(
      ctx.event.project,
      ctx.event.mrId,
      `## ✅ Doc-Bot Updates Created\n\nI've created a merge request with documentation updates:\n\n➡️ ${mrUrl}\n\n### Modified Files\n\n${result.modifiedFiles.map((f) => `- \`${f}\``).join('\n')}\n\n---\n\n<sub>Cost: $${result.cost.toFixed(4)} | Turns: ${result.turns} | Session: ${result.sessionId.substring(0, 12)}</sub>`
    );

    logger.info({ mrUrl, modifiedFiles: result.modifiedFiles }, 'Same-repo MR created');
  } catch (error) {
    logger.error({ error }, 'Failed to process same-repo updates');
    await ctx.platform.postComment(
      ctx.event.project,
      ctx.event.mrId,
      `## ❌ Doc-Bot Error\n\nFailed to create documentation updates: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  } finally {
    await ctx.gitManager.cleanup(workDir);
  }
}

/**
 * Process cross-repo documentation updates
 */
async function processCrossRepoUpdates(
  ctx: WorkflowContext,
  apiKey: string,
  sessionStore: SessionStore,
  targets: DocTarget[],
  userInstructions?: string
): Promise<void> {
  logger.info({ targetCount: targets.length }, 'Processing cross-repo updates');

  // Group targets by docs repo
  const repoGroups = new Map<string, DocTarget[]>();
  for (const target of targets) {
    if (!target.docsRepo) continue;
    const existing = repoGroups.get(target.docsRepo) || [];
    existing.push(target);
    repoGroups.set(target.docsRepo, existing);
  }

  // Process each docs repo
  for (const [docsRepo, repoTargets] of repoGroups.entries()) {
    await processSingleCrossRepo(
      ctx,
      apiKey,
      sessionStore,
      docsRepo,
      repoTargets,
      userInstructions
    );
  }
}

/**
 * Process updates for a single cross-repo docs repository
 */
async function processSingleCrossRepo(
  ctx: WorkflowContext,
  apiKey: string,
  sessionStore: SessionStore,
  docsRepo: string,
  targets: DocTarget[],
  userInstructions?: string
): Promise<void> {
  logger.info({ docsRepo, targetCount: targets.length }, 'Processing single cross-repo');

  // Determine which platform the docs repo is on
  const docsRepoInfo = parseRepoUrl(docsRepo);
  const docsPlatform = ctx.platformResolver.getPlatform(docsRepoInfo.platform);

  if (!docsPlatform) {
    logger.error({ platform: docsRepoInfo.platform }, 'Docs platform not configured');
    await ctx.platform.postComment(
      ctx.event.project,
      ctx.event.mrId,
      `## ❌ Doc-Bot Error\n\nDocs repository platform (${docsRepoInfo.platform}) is not configured.`
    );
    return;
  }

  try {
    // Clone docs repo
    const docsCloneUrl = await docsPlatform.getAuthenticatedCloneUrl(docsRepoInfo.project);
    const branchName = `doc-bot/${ctx.event.platform}-${ctx.event.project.replace(/\//g, '-')}-mr-${ctx.event.mrId}`;

    const { git, workDir } = await ctx.gitManager.clone({
      repoUrl: docsCloneUrl,
      branch: 'main', // or detect default branch
    });

    try {
      // Create branch
      await ctx.gitManager.createBranch(git, branchName);

      // Run agent with tools
      const agent = new AgentOrchestrator({
        apiKey,
        model: ctx.config.model,
        maxTurns: ctx.config.maxTurns,
        workDir,
        styleGuide: ctx.styleGuide,
      });

      const prompt = buildUpdatePromptWithTools(
        ctx.diff,
        targets,
        ctx.changedFiles,
        ctx.styleGuide,
        userInstructions,
        false // cross-repo mode
      );

      const result = await agent.run(prompt, undefined, true);

      // Store session
      sessionStore.set(
        {
          platform: ctx.event.platform,
          project: ctx.event.project,
          mrId: ctx.event.mrId,
        },
        result.sessionId
      );

      if (result.modifiedFiles.length === 0) {
        await ctx.platform.postComment(
          ctx.event.project,
          ctx.event.mrId,
          `## 📝 Doc-Bot Analysis (${docsRepo})\n\n${result.response}\n\n*No documentation changes were needed.*\n\n<sub>Cost: $${result.cost.toFixed(4)}</sub>`
        );
        return;
      }

      // Commit changes
      await ctx.gitManager.commit(git, {
        files: result.modifiedFiles,
        message: `docs: update for ${ctx.event.project} changes\n\nAutomatic documentation updates based on code changes in:\n${ctx.event.repoUrl}/merge_requests/${ctx.event.mrId}`,
        authorName: 'Doc-Bot',
        authorEmail: 'doc-bot@localhost',
      });

      // Push branch
      await ctx.gitManager.push(git, branchName);

      // Create MR/PR in docs repo
      const mrResult = await docsPlatform.openMR(docsRepoInfo.project, {
        sourceBranch: branchName,
        targetBranch: 'main',
        title: `docs: Update for ${ctx.event.project} changes`,
        description: `## Automated Documentation Updates\n\nThis MR contains documentation updates based on code changes in:\n\n**Source**: ${ctx.event.repoUrl}/merge_requests/${ctx.event.mrId}\n\n### Changes\n\n${result.modifiedFiles.map((f) => `- \`${f}\``).join('\n')}\n\n### Agent Summary\n\n${result.response}\n\n---\n\n<sub>Generated by Doc-Bot | Cost: $${result.cost.toFixed(4)}</sub>`,
      });
      const mrUrl = mrResult.webUrl;

      // Post comment with cross-repo MR link
      await ctx.platform.postComment(
        ctx.event.project,
        ctx.event.mrId,
        `## ✅ Doc-Bot Updates Created (Cross-Repo)\n\nI've created a merge request in the documentation repository:\n\n**Docs Repo**: ${docsRepo}\n➡️ ${mrUrl}\n\n### Modified Files\n\n${result.modifiedFiles.map((f) => `- \`${f}\``).join('\n')}\n\n---\n\n<sub>Cost: $${result.cost.toFixed(4)} | Turns: ${result.turns}</sub>`
      );

      logger.info({ mrUrl, docsRepo, modifiedFiles: result.modifiedFiles }, 'Cross-repo MR created');
    } finally {
      await ctx.gitManager.cleanup(workDir);
    }
  } catch (error) {
    logger.error({ error, docsRepo }, 'Failed to process cross-repo updates');
    await ctx.platform.postComment(
      ctx.event.project,
      ctx.event.mrId,
      `## ❌ Doc-Bot Error (Cross-Repo)\n\nFailed to create documentation updates in ${docsRepo}: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  }
}

/**
 * Parse repository URL to determine platform and project
 */
function parseRepoUrl(url: string): { platform: 'gitlab' | 'github'; project: string } {
  const urlObj = new URL(url);

  // Determine platform from hostname
  const platform = urlObj.hostname.includes('github') ? 'github' : 'gitlab';

  // Extract project path (remove .git if present)
  const project = urlObj.pathname.replace(/^\//, '').replace(/\.git$/, '');

  return { platform, project };
}
