import { TaskConfig, saveTaskConfig } from './config';
import { PlatformResolver } from '../platform/resolver';
import { GitManager } from '../git/manager';
import { loadConfig, parseChangedFiles, findAffectedDocTargets } from '../util/config-loader';
import { updateWorkflowFull } from '../workflows/update-full';
import { SessionStore } from '../agent/session-store';
import { logger } from '../util/logger';
import { join } from 'path';
import { readFile } from 'fs/promises';
import { PlatformEvent } from '../platform/interface';

/**
 * Task executor for running doc-bot in iterative/active mode
 * Instead of waiting for webhooks, this allows manual execution against a branch
 */
export class TaskExecutor {
  constructor(
    private platformResolver: PlatformResolver,
    private gitManager: GitManager,
    private apiKey: string,
    private sessionStore: SessionStore
  ) {}

  /**
   * Execute a task from configuration
   */
  async execute(taskConfig: TaskConfig, configPath: string): Promise<void> {
    logger.info({ taskConfig }, 'Starting task execution');

    const platform = this.platformResolver.getPlatform(taskConfig.platform);
    if (!platform) {
      throw new Error(`Platform ${taskConfig.platform} is not configured`);
    }

    try {
      // Clone the repository
      const cloneUrl = await platform.getAuthenticatedCloneUrl(taskConfig.project);
      const { git, workDir } = await this.gitManager.clone({
        repoUrl: cloneUrl,
        branch: taskConfig.branch,
      });

      try {
        // Get diff between branch and base branch
        const diffResult = await git.diff([`${taskConfig.baseBranch}...${taskConfig.branch}`]);

        if (!diffResult || diffResult.trim().length === 0) {
          logger.info('No changes detected between branches');
          console.log('✅ No changes detected between branches - nothing to do');
          return;
        }

        // Parse changed files
        const changedFiles = parseChangedFiles(diffResult);
        logger.info({ changedFiles }, 'Changed files detected');

        // Load .doc-bot.yaml config
        const configFilePath = join(workDir, '.doc-bot.yaml');
        const docBotConfig = await loadConfig(configFilePath);

        // Check for affected doc targets
        const affectedTargets = findAffectedDocTargets(docBotConfig, changedFiles);

        if (affectedTargets.length === 0) {
          logger.info('No documentation targets affected');
          console.log('✅ No documentation targets affected - nothing to do');
          return;
        }

        logger.info({ affectedTargets: affectedTargets.length }, 'Documentation targets affected');

        // Load style guide if specified
        let styleGuide: string | undefined;
        if (docBotConfig.styleGuide) {
          const styleGuidePath = join(workDir, docBotConfig.styleGuide);
          try {
            styleGuide = await readFile(styleGuidePath, 'utf-8');
          } catch (error) {
            logger.warn({ path: docBotConfig.styleGuide }, 'Style guide not found');
          }
        }

        // Check if PR/MR already exists
        let prNumber = taskConfig.pr;
        let prUrl: string | undefined;

        if (!prNumber) {
          // Create a PR/MR for tracking
          logger.info('No PR specified, creating one');

          const prTitle = `docs: Update documentation for ${taskConfig.branch}`;
          const prDescription = `## Automated Documentation Updates\n\nThis PR/MR tracks documentation updates for changes in branch \`${taskConfig.branch}\`.\n\n${taskConfig.instructions ? `### Instructions\n\n${taskConfig.instructions}\n\n` : ''}---\n\n*Generated by Doc-Bot Task Mode*`;

          const mrResult = await platform.openMR(taskConfig.project, {
            sourceBranch: taskConfig.branch,
            targetBranch: taskConfig.baseBranch,
            title: prTitle,
            description: prDescription,
          });

          prUrl = mrResult.webUrl;
          prNumber = mrResult.mrId;

          // Update task config with PR number
          taskConfig.pr = prNumber;
          await saveTaskConfig(configPath, taskConfig);

          logger.info({ prNumber, prUrl }, 'Created PR/MR and updated task config');
          console.log(`✅ Created PR/MR #${prNumber}: ${prUrl}`);
        } else {
          logger.info({ prNumber }, 'Using existing PR/MR');
        }

        if (!prNumber) {
          throw new Error('Failed to determine PR/MR number');
        }

        // Create a synthetic platform event
        const event: PlatformEvent = {
          type: 'mr_opened',
          platform: taskConfig.platform,
          project: taskConfig.project,
          mrId: prNumber,
          sourceBranch: taskConfig.branch,
          targetBranch: taskConfig.baseBranch,
          repoUrl: taskConfig.repo,
          eventId: `task-${Date.now()}`,
        };

        // Create workflow context
        const ctx = {
          event,
          platform,
          platformResolver: this.platformResolver,
          gitManager: this.gitManager,
          config: docBotConfig,
          diff: diffResult,
          changedFiles,
          styleGuide,
        };

        // Run the full update workflow
        console.log('🤖 Running documentation update workflow...');
        await updateWorkflowFull(ctx, this.apiKey, this.sessionStore, taskConfig.instructions);

        console.log('✅ Task execution completed');
        logger.info('Task execution completed successfully');
      } finally {
        await this.gitManager.cleanup(workDir);
      }
    } catch (error) {
      logger.error({ error }, 'Task execution failed');
      throw error;
    }
  }

  /**
   * Dry run - analyze what would be done without making changes
   */
  async dryRun(taskConfig: TaskConfig): Promise<void> {
    logger.info({ taskConfig }, 'Starting dry run');

    const platform = this.platformResolver.getPlatform(taskConfig.platform);
    if (!platform) {
      throw new Error(`Platform ${taskConfig.platform} is not configured`);
    }

    console.log('🔍 Dry run mode - analyzing changes...');

    try {
      const cloneUrl = await platform.getAuthenticatedCloneUrl(taskConfig.project);
      const { git, workDir } = await this.gitManager.clone({
        repoUrl: cloneUrl,
        branch: taskConfig.branch,
      });

      try {
        const diffResult = await git.diff([`${taskConfig.baseBranch}...${taskConfig.branch}`]);

        if (!diffResult || diffResult.trim().length === 0) {
          console.log('✅ No changes detected');
          return;
        }

        const changedFiles = parseChangedFiles(diffResult);
        console.log(`\n📝 Changed files (${changedFiles.length}):`);
        changedFiles.forEach((f) => console.log(`   - ${f}`));

        const configFilePath = join(workDir, '.doc-bot.yaml');
        const docBotConfig = await loadConfig(configFilePath);

        const affectedTargets = findAffectedDocTargets(docBotConfig, changedFiles);

        if (affectedTargets.length === 0) {
          console.log('\n✅ No documentation targets affected');
          return;
        }

        console.log(`\n📚 Affected documentation targets (${affectedTargets.length}):`);
        affectedTargets.forEach((t) => {
          console.log(`   - ${t.docsPath} (${t.mode})`);
          if (t.docsRepo) {
            console.log(`     Docs repo: ${t.docsRepo}`);
          }
        });

        console.log(`\n💡 Run without --dry-run to create documentation updates`);
      } finally {
        await this.gitManager.cleanup(workDir);
      }
    } catch (error) {
      logger.error({ error }, 'Dry run failed');
      throw error;
    }
  }
}
